packages:
  - packages/*
  - apps/*

patchedDependencies:
  dts-buddy: patches/dts-buddy.patch
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
